In [4]:
import numpy as np

In [5]:
x = np.random.randint(1,10)
print(x)


6


In [13]:
x = np.random.randint(1,10,size=8)
print(x)


[8 9 1 2 9 8 9 8]


In [17]:
x = 50+2*np.random.random(size=15)
x = x.round(decimals=2)
print(x)


[50.36 50.75 50.15 51.43 50.21 51.58 51.22 50.49 50.99 51.97 51.71 50.89
 50.77 51.05 51.12]


In [11]:
x = np.random.rand(3,3)
print(x)


[[0.14960518 0.7829787  0.53679664]
 [0.81810208 0.58946175 0.26872743]
 [0.1942787  0.16919586 0.92784603]]
