In [2]:
import numpy as np
import pandas as pd
matrix_data = np.random.randint(1,10,size=20).reshape(5,4)
print(matrix_data)

[[7 2 1 7]
 [2 5 8 6]
 [5 6 3 6]
 [4 9 6 5]
 [6 1 6 7]]


In [3]:
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']


In [4]:
df = pd.DataFrame(data=matrix_data, index=row_labels,
                  columns=column_headings)


In [5]:
print("\nThe data frame looks like\n",'-'*45, sep='')
print(df) 



The data frame looks like
---------------------------------------------
   W  X  Y  Z
A  7  2  1  7
B  2  5  8  6
C  5  6  3  6
D  4  9  6  5
E  6  1  6  7


In [10]:
d={'auto':[10,20,30],'bunny':[30,40,50],'carrot':[50,60,70]}

In [11]:
df2=pd.DataFrame(data=d,index=['X','Y','Z'])
print(df2)


   auto  bunny  carrot
X    10     30      50
Y    20     40      60
Z    30     50      70
