In [1]:
import numpy as np
matrix_1 = np.random.randint(1,10,9).reshape(3,3)
matrix_2 = np.random.randint(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n",matrix_1)
print("\n2nd Matrix of random single-digit numbers\n",matrix_2)



1st Matrix of random single-digit numbers
 [[2 3 9]
 [2 2 3]
 [9 3 6]]

2nd Matrix of random single-digit numbers
 [[1 9 5]
 [4 4 4]
 [9 9 1]]


In [2]:
print("\nAddition\n", matrix_1+matrix_2)
print("\nMultiplication\n", matrix_1*matrix_2)
print("\nDivision\n", matrix_1/matrix_2)
print("\nLinear combination: 3*A - 2*B\n", 3*matrix_1-2*matrix_2)



Addition
 [[ 3 12 14]
 [ 6  6  7]
 [18 12  7]]

Multiplication
 [[ 2 27 45]
 [ 8  8 12]
 [81 27  6]]

Division
 [[2.         0.33333333 1.8       ]
 [0.5        0.5        0.75      ]
 [1.         0.33333333 6.        ]]

Linear combination: 3*A - 2*B
 [[ 4 -9 17]
 [-2 -2  1]
 [ 9 -9 16]]


In [9]:
print("\nAddition of a scalar (100)\n", 100+matrix_1)

print("\nExponentiation, matrix cubed here\n", matrix_1**3)
print("\nExponentiation, square root using 'pow' function\n",pow(matrix_1,0.5))
print("\n", (np.sqrt(matrix_1)))



Addition of a scalar (100)
 [[102 103 109]
 [102 102 103]
 [109 103 106]]

Exponentiation, matrix cubed here
 [[  8  27 729]
 [  8   8  27]
 [729  27 216]]

Exponentiation, square root using 'pow' function
 [[1.41421356 1.73205081 3.        ]
 [1.41421356 1.41421356 1.73205081]
 [3.         1.73205081 2.44948974]]

 [[1.41421356 1.73205081 3.        ]
 [1.41421356 1.41421356 1.73205081]
 [3.         1.73205081 2.44948974]]
