1. Create an array of 30 random integers

In [1]:
import numpy as np
a = np.random.randint(1,100,30) 

b = a.reshape(2,3,5) 

c = a.reshape(6,5) 

2. Print the shape using the shape

In [2]:
print ("Shape of a:", a.shape) 

print ("Shape of b:", b.shape) 

print ("Shape of c:", c.shape) 

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


3. Print the arrays a, b, and c 

In [3]:
print("\na looks like\n",a) 

print("\nb looks like\n",b) 

print("\nc looks like\n",c) 


a looks like
 [80 55 67  2 90 65 15 58 83 21 54 52 71 71 56 41 74 83 35 82 19 90 80 47
 91 92 97 54 35 93]

b looks like
 [[[80 55 67  2 90]
  [65 15 58 83 21]
  [54 52 71 71 56]]

 [[41 74 83 35 82]
  [19 90 80 47 91]
  [92 97 54 35 93]]]

c looks like
 [[80 55 67  2 90]
 [65 15 58 83 21]
 [54 52 71 71 56]
 [41 74 83 35 82]
 [19 90 80 47 91]
 [92 97 54 35 93]]


In [5]:
b_flat = b.ravel()
print(b_flat)


[36 21  3 16 37 59 89  9  6 83 25 55 21 92  1 56 62 19 85 93 63 33 47 13
 37 85 43  4 38 50]
