In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3] 
list_1

[1, 2, 3]

In [3]:
array_1 = np.array(list_1)
array_1

array([1, 2, 3])

In [4]:
a = np.array([1.2, 3.4, 5.6]) 
a 

array([1.2, 3.4, 5.6])

In [5]:
type(a)

numpy.ndarray

In [6]:
type(array_1)

numpy.ndarray

In [7]:
type(list_1)

list

In [8]:
data = np.genfromtxt('../datasets/stock.csv', delimiter=',', names=True,dtype=None, encoding='ascii')
data

array([('MMM', 100), ('AOS', 101), ('ABT', 102), ('ABBV', 103),
       ('ACN', 104), ('ATVI', 105), ('AYI', 106), ('ADBE', 107),
       ('AAP', 108), ('AMD', 109), ('AES', 110), ('AET', 111),
       ('AMG', 112), ('AFL', 113), ('A', 114), ('APD', 115),
       ('AKAM', 116), ('ALK', 117), ('ALB', 118), ('ARE', 119),
       ('ALXN', 120), ('ALGN', 121), ('ALLE', 122), ('AGN', 123),
       ('ADS', 124), ('LNT', 125), ('ALL', 126), ('GOOGL', 127),
       ('GOOG', 128), ('MO', 129), ('AMZN', 130), ('AEE', 131),
       ('AAL', 132), ('AEP', 133), ('AXP', 134), ('AIG', 135),
       ('AMT', 136), ('AWK', 137), ('AMP', 138), ('ABC', 139),
       ('AME', 140), ('AMGN', 141), ('APH', 142), ('APC', 143),
       ('ADI', 144), ('ANDV', 145), ('ANSS', 146), ('ANTM', 147),
       ('AON', 148)], dtype=[('Symbol', '<U5'), ('Price', '<i8')])

In [9]:
type(data)

numpy.ndarray

In [10]:
data = np.genfromtxt('../datasets/numbers.csv', delimiter=',', names=True)
data = data.astype('float64')
data + data

array([202., 204., 206., 208., 210., 212., 214., 216., 218., 220., 222.,
       224., 226., 228., 230., 232., 234., 236., 238., 240., 242., 244.,
       246., 248., 250., 252., 254., 256., 258., 260., 262., 264., 266.,
       268., 270., 272., 274., 276., 278., 280., 282., 284., 286., 288.,
       290., 292., 294., 296.])